version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/marketforge

hooks:
  BeforeInstall:
    # 1. Sahipliği ayarla: npm'den önce çalışmalı.
    - location: scripts/change_ownership.sh
      timeout: 300
      runas: root

    # Mevcut before_install.sh betiğiniz (eğer varsa)
    # - location: scripts/before_install.sh
    #   timeout: 300

  AfterInstall:
    # 2. Kurulumu yap: Bu betik içindeki sudo ile çalışacak.
    - location: scripts/after_install.sh
      timeout: 300
      runas: ubuntu # Bu kullanıcı sudo yetkisi kullanacak.

  ApplicationStart:
    # 3. Sunucuyu başlat: npm install burada OLMAMALI!
    - location: scripts/start_server.sh
      timeout: 300
      runas: ubuntu
