version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/marketforge

hooks:
  BeforeInstall:
    # 💥 KRİTİK: NVM ve Node.js'i kurun. (Timeout süresini artırın)
    - location: scripts/before_install.sh
      timeout: 600
      runas: root

    # 1. Sahipliği ayarla (Kurulumdan sonra da NVM klasörlerini garantiye alın)
    - location: scripts/change_ownership.sh
      timeout: 300
      runas: root

    # 2. node_modules klasörünü root olarak sil.
    - location: scripts/remove_node_modules.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: ubuntu

  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ubuntu
