version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - rm -rf node_modules
      - npm install

  pre_build:
    commands:
      - npm test

  build:
    commands:
      - mkdir -p artifact
      - cp -r app.js server.js utils.js package.json node_modules appspec.yml scripts artifact/

artifacts:
  base-directory: artifact
  files:
    - "**/*"
